# Generated by Django 4.2.8 on 2024-09-08 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inference_runs',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region_code', models.CharField(choices=[('ASUNCION', 'ASUNCION'), ('GRAN_ASUNCION', 'GRAN_ASUNCION'), ('CHACO', 'CHACO')], max_length=255)),
                ('bbox', models.CharField(max_length=255)),
                ('has_weather_data', models.BooleanField(default=False)),
                ('has_pattern_station', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_station_on', models.BooleanField(default=False)),
                ('is_pattern_station', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.regions')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='StationReadingsGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_localtime', models.DateTimeField()),
                ('pm1', models.FloatField(blank=True, null=True)),
                ('pm2_5', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('pm2_5_avg_6h', models.FloatField(blank=True, null=True)),
                ('pm2_5_max_6h', models.FloatField(blank=True, null=True)),
                ('pm2_5_skew_6h', models.FloatField(blank=True, null=True)),
                ('pm2_5_std_6h', models.FloatField(blank=True, null=True)),
                ('aqi_pm2_5', models.FloatField(blank=True, null=True)),
                ('aqi_pm10', models.FloatField(blank=True, null=True)),
                ('aqi_level', models.IntegerField(blank=True, null=True)),
                ('aqi_pm2_5_max_24h', models.FloatField(blank=True, null=True)),
                ('aqi_pm2_5_skew_24h', models.FloatField(blank=True, null=True)),
                ('aqi_pm2_5_std_24h', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stations')),
            ],
            options={
                'db_table': 'station_readings_gold',
            },
        ),
        migrations.CreateModel(
            name='InferenceResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_6h', models.JSONField(blank=True, null=True)),
                ('forecast_12h', models.JSONField(blank=True, null=True)),
                ('aqi_input', models.JSONField(blank=True, null=True)),
                ('inference_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.inferenceruns')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stations')),
            ],
            options={
                'db_table': 'inference_results',
            },
        ),
    ]
