# Generated by Django 4.2.8 on 2024-03-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='aqi',
        ),
        migrations.CreateModel(
            name='StationValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pm1', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('aqi_pm2_5', models.FloatField()),
                ('aqi_pm10', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.station')),
            ],
        ),
        migrations.CreateModel(
            name='AreaValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('aqi_pm2_5', models.FloatField()),
                ('aqi_pm10', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.area')),
            ],
        ),
    ]
