# Generated by Django 4.2.8 on 2024-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_area_remove_station_aqi_stationvalues_areavalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StationValues',
            new_name='StationReadings',
        ),
        migrations.RemoveField(
            model_name='areavalues',
            name='area',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_id',
        ),
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.CharField(choices=[('ASUNCION', 'Asuncion'), ('CENTRAL', 'Central'), ('PRESIDENTE HAYES', 'Chaco')], default='ASUNCION', max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='AreaValues',
        ),
    ]
