# Generated by Django 4.2.8 on 2024-09-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='active_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='is_station_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='station',
            name='online_since',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='StationReadings',
        ),
    ]
