# Generated by Django 4.2.8 on 2024-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_forecasts_rename_station_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecasts',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forecasts',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
