# Generated by Django 4.2.8 on 2024-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_forecasts_timestamp_forecasts_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='current_aqi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='forecast',
            field=models.ManyToManyField(to='api.forecasts'),
        ),
        migrations.AddField(
            model_name='stations',
            name='last_calculated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
