# Generated by Django 4.2.8 on 2024-09-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stations_current_aqi_stations_forecast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.IntegerField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forecasts')),
                ('stations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stations')),
            ],
        ),
    ]
