# Generated by Django 4.2.30 on 2026-09-07 02:55

from django.db import migrations, models
import django.db.models.deletion

from api.schema_moves import is_postgresql, move_tables

TABLE_NAME = "institution_alert_rule_state"


def _move_to_django_admin(apps, schema_editor):
    """Django-owned, so it belongs in ``django_admin`` like every table in 0019.

    A no-op on SQLite, which has no schemas at all, and on any database where
    the table is already in place — the migration role is scoped to
    ``django_admin`` and holds no CREATE privilege on the database, so nothing
    here may issue DDL unconditionally. See api/schema_moves.py.
    """
    if not is_postgresql(schema_editor):
        return
    with schema_editor.connection.cursor() as cursor:
        move_tables(cursor, "django_admin", [TABLE_NAME])


def _reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_institution_alert_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionAlertRuleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_firing",
                    models.BooleanField(
                        default=False,
                        help_text="True while followers have been warned and the air has not yet fallen back below the rearm band.",
                    ),
                ),
                (
                    "last_aqi",
                    models.FloatField(
                        blank=True,
                        help_text="The most recent reading this rule was evaluated against.",
                        null=True,
                    ),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="api.institutionalertrule",
                    ),
                ),
            ],
            options={
                "db_table": "institution_alert_rule_state",
            },
        ),
        migrations.RunPython(_move_to_django_admin, _reverse_noop),
    ]
