# Generated by Django 4.2.30 on 2026-09-07 02:55

from django.db import migrations, models
import django.db.models.deletion

TABLE_NAME = "institution_alert_rule_state"


def _move_to_django_admin(apps, schema_editor):
    """Django-owned, so it belongs in ``django_admin`` like every table in 0019.

    A no-op on SQLite, which has no schemas at all.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('CREATE SCHEMA IF NOT EXISTS "django_admin"')
        cursor.execute(
            """
            SELECT table_schema FROM information_schema.tables
            WHERE table_name = %s
              AND table_schema NOT IN ('pg_catalog', 'information_schema')
            """,
            [TABLE_NAME],
        )
        schemas = {row[0] for row in cursor.fetchall()}
        if "django_admin" in schemas or not schemas:
            return
        source_schema = "public" if "public" in schemas else next(iter(schemas))
        cursor.execute(
            f'ALTER TABLE "{source_schema}"."{TABLE_NAME}" '
            'SET SCHEMA "django_admin"'
        )


def _reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_institution_alert_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAlertRuleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_firing', models.BooleanField(default=False, help_text='True while followers have been warned and the air has not yet fallen back below the rearm band.')),
                ('last_aqi', models.FloatField(blank=True, help_text='The most recent reading this rule was evaluated against.', null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='api.institutionalertrule')),
            ],
            options={
                'db_table': 'institution_alert_rule_state',
            },
        ),
        migrations.RunPython(_move_to_django_admin, _reverse_noop),
    ]
