"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path
from typing import Any

from .telemetry import initialize_glitchtip

load_dotenv()


def _quote_postgres_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _env_bool(key: str, default: bool) -> bool:
    value = os.getenv(key)
    if value is None:
        return default
    normalized = value.strip()
    if normalized == "":
        return default
    return normalized.lower() in {"1", "true", "yes", "on"}


def _env_int(key: str, default: int) -> int:
    value = os.getenv(key)
    if value is None or value.strip() == "":
        return default
    return int(value)


def _env_str(key: str, default: str) -> str:
    value = os.getenv(key)
    if value is None:
        return default
    normalized = value.strip()
    if normalized == "":
        return default
    return normalized


def _env_list(key: str) -> list[str]:
    return [item.strip() for item in os.getenv(key, "").split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("BACKEND_SECRET_KEY", "respira-backend-dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("BACKEND_DEBUG", "false").lower() == "true"

initialize_glitchtip(
    dsn=os.getenv("BACKEND_GLITCHTIP_DSN", "").strip(),
    environment=os.getenv("GLITCHTIP_ENVIRONMENT", "").strip(),
    release=os.getenv("GLITCHTIP_RELEASE", "").strip(),
)

_default_allowed_hosts = [
    "127.0.0.1",
    "localhost",
    "backend",
    "testserver",
    "159.65.227.146",
    "proyectorespira.net",
    ".proyectorespira.net",
]

ALLOWED_HOSTS = list(
    dict.fromkeys(_default_allowed_hosts + _env_list("BACKEND_ALLOWED_HOSTS"))
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "axes",
    "accounts",
    "api",
]

# Custom user model authenticated by email (see accounts app).
AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Scoped, so only the endpoints that opt in are throttled — today that is
    # the unauthenticated device-follower API (api.views.DeviceFollowerViewSet).
    # The rate is counted per client IP and mobile carriers put many phones
    # behind a single CGNAT address, so it is deliberately generous: it bounds
    # abuse without cutting off a whole network.
    "DEFAULT_THROTTLE_RATES": {
        "device_followers": _env_str("BACKEND_DEVICE_FOLLOWER_THROTTLE", "120/min"),
        # Password recovery (api.views.InstitutionViewSet). Counted per client
        # IP, and much tighter than the follower API: this endpoint sends mail
        # to an address the caller chose, so the rate is what stops it being
        # used to flood somebody's inbox or to walk a list of addresses.
        "password_reset": _env_str("BACKEND_PASSWORD_RESET_THROTTLE", "10/hour"),
        # Setting the new password. Looser than the request above because
        # nothing is sent anywhere and a visitor may legitimately need several
        # tries to satisfy the password rules, but still bounded so the reset
        # tokens themselves cannot be brute-forced.
        "password_reset_confirm": _env_str(
            "BACKEND_PASSWORD_RESET_CONFIRM_THROTTLE", "30/hour"
        ),
    },
}

# How many stations one installation may follow (api.views.DeviceFollowerView).
# A bound on abuse of an unauthenticated endpoint rather than a product limit,
# which is why it is configurable here rather than a database constraint.
MAX_FOLLOWS_PER_INSTALLATION = _env_int("BACKEND_MAX_FOLLOWS_PER_INSTALLATION", 10)

# Whether the per-sensor push alerts actually go out (api.push).
# Off by default so a freshly deployed environment cannot start notifying real
# devices before somebody decides it should; the management command still
# offers --dry-run and --force.
SENSOR_ALERTS_ENABLED = _env_bool("BACKEND_SENSOR_ALERTS_ENABLED", False)

SPECTACULAR_SETTINGS = {
    "TITLE": "RespiraAPI",
    "DESCRIPTION": "This is the Respira API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "backend.middleware.GlitchTipUserContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    # AxesMiddleware must be the last middleware in the stack.
    "axes.middleware.AxesMiddleware",
]

CORS_ORIGIN_ALLOW_ALL = False

# Use the environment variable instead of hardcoded whitelist
# cors_allowed_origins is already defined above

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

postgres_config: dict[str, str | None] = {
    "NAME": os.getenv("BACKEND_POSTGRES_DB"),
    "USER": os.getenv("BACKEND_POSTGRES_USER"),
    "PASSWORD": os.getenv("BACKEND_POSTGRES_PASSWORD"),
    "HOST": os.getenv("BACKEND_POSTGRES_HOST"),
    "PORT": os.getenv("BACKEND_POSTGRES_PORT"),
}

DATABASES: dict[str, dict[str, Any]]

if all(postgres_config.values()):
    postgres_config_clean = {
        key: value for key, value in postgres_config.items() if value is not None
    }
    db_options: dict[str, str] = {}
    sslmode = os.getenv("BACKEND_POSTGRES_SSLMODE")
    if sslmode:
        db_options["sslmode"] = sslmode

    sslrootcert = os.getenv("BACKEND_POSTGRES_SSLROOTCERT")
    if sslrootcert:
        db_options["sslrootcert"] = sslrootcert

    sslcert = os.getenv("BACKEND_POSTGRES_SSLCERT")
    if sslcert:
        db_options["sslcert"] = sslcert

    sslkey = os.getenv("BACKEND_POSTGRES_SSLKEY")
    if sslkey:
        db_options["sslkey"] = sslkey

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            **postgres_config_clean,
            "OPTIONS": db_options,
        }
    }

    # search_path is a FIXED contract, not a configurable one: django_admin
    # (Django-owned tables: auth, admin, accounts, and every operational
    # model in api/models.py) always resolves before respira_gold (tables
    # the data pipeline owns and writes — dbt SQL for
    # stations/regions/*_readings_gold, the Prefect inference flow for
    # inference_runs/inference_results; see api.gold.ReadOnlyGoldModel,
    # which blocks writes to these from the backend regardless of
    # search_path). `public` stays last for extensions and any table this
    # project does not itself define.
    #
    # This order can never create ambiguity: django_admin and respira_gold
    # do not share a single table name (verified — see the regression test
    # in api/tests_schema_ownership.py), so which one search_path checks
    # first cannot change which table a query resolves to. That test is
    # exactly what would fail if a future table name collided.
    #
    # BACKEND_POSTGRES_SCHEMA no longer controls resolution order — it used
    # to, and that was the bug: an operator-configurable order is exactly
    # what let an unqualified table name resolve to the wrong schema. It is
    # kept only so extra, unrelated schemas (custom Postgres extensions,
    # say) can still be appended after the fixed prefix.
    _fixed_schemas = {"django_admin", "respira_gold", "public"}
    extra_schemas = [
        schema.strip()
        for schema in os.getenv("BACKEND_POSTGRES_SCHEMA", "").split(",")
        if schema.strip() and schema.strip().lower() not in _fixed_schemas
    ]
    quoted_schemas = ['"django_admin"', '"respira_gold"', '"public"'] + [
        _quote_postgres_identifier(schema) for schema in extra_schemas
    ]
    default_db = DATABASES["default"]
    db_options_map = default_db.setdefault("OPTIONS", {})
    db_options_map["options"] = f"-c search_path={','.join(quoted_schemas)}"
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": _env_int("BACKEND_PASSWORD_MIN_LENGTH", 10),
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "accounts.validators.ComplexityValidator",
        "OPTIONS": {
            "require_special": _env_bool("BACKEND_PASSWORD_REQUIRE_SPECIAL", True),
        },
    },
]


# Authentication
# The Django Admin backoffice authenticates against the custom user model
# (accounts.User) using Django's built-in session framework and the default
# ModelBackend. See docs/admin-auth-configuration.md.

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend must be first so failed logins are recorded and
    # locked-out requests are rejected before ModelBackend runs.
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Django Admin provides the login/logout views. LOGIN_URL points unauthenticated
# requests for protected pages at the admin login form.
LOGIN_URL = "admin:login"
LOGIN_REDIRECT_URL = "admin:index"

# Session management (environment-aware).
# Default session lifetime: 8 hours. Sessions are stored in the database.
SESSION_COOKIE_AGE = _env_int("BACKEND_SESSION_COOKIE_AGE", 60 * 60 * 8)
SESSION_EXPIRE_AT_BROWSER_CLOSE = _env_bool(
    "BACKEND_SESSION_EXPIRE_AT_BROWSER_CLOSE", False
)
SESSION_SAVE_EVERY_REQUEST = _env_bool("BACKEND_SESSION_SAVE_EVERY_REQUEST", False)

# Secure cookie settings. Secure cookies (HTTPS-only) are enabled by default
# whenever DEBUG is off (i.e. in production) and can be overridden per
# environment. HttpOnly session cookies are always on so client-side JS cannot
# read the session id.
_secure_cookies_default = not DEBUG
SESSION_COOKIE_SECURE = _env_bool(
    "BACKEND_SESSION_COOKIE_SECURE", _secure_cookies_default
)
CSRF_COOKIE_SECURE = _env_bool("BACKEND_CSRF_COOKIE_SECURE", _secure_cookies_default)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = _env_str("BACKEND_SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = _env_str("BACKEND_CSRF_COOKIE_SAMESITE", "Lax")

# Origins trusted for CSRF-protected admin POSTs when served over HTTPS behind a
# proxy (e.g. https://proyectorespira.net). Configure per deployment.
CSRF_TRUSTED_ORIGINS = _env_list("BACKEND_CSRF_TRUSTED_ORIGINS")


# Email / password recovery
# Django's built-in password reset workflow is enabled as soon as SMTP settings
# are provided; no additional development is required. In development, emails are
# printed to the console. See docs/admin-password-management.md.
EMAIL_BACKEND = os.getenv(
    "BACKEND_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.getenv("BACKEND_EMAIL_HOST", "")
EMAIL_PORT = _env_int("BACKEND_EMAIL_PORT", 587)
EMAIL_HOST_USER = os.getenv("BACKEND_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("BACKEND_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("BACKEND_EMAIL_USE_TLS", True)
DEFAULT_FROM_EMAIL = _env_str(
    "BACKEND_DEFAULT_FROM_EMAIL", "no-reply@proyectorespira.net"
)

# How long a password reset link stays valid, for both the admin flow
# (backend/backend/urls.py) and the institutional one (api.views). Django's own
# default is three days; one day is short enough that a link left sitting in an
# inbox stops working, and long enough for somebody who requests a reset before
# a weekend. The token is invalidated earlier than this by any password change.
PASSWORD_RESET_TIMEOUT = _env_int("BACKEND_PASSWORD_RESET_TIMEOUT_HOURS", 24) * 3600

# Where the institutional reset email points. Only the path is configured: the
# scheme and host come from the request that asked for the reset, so the link
# resolves to whichever environment the user is on rather than a hardcoded one.
# An absolute URL here overrides that, for the case where the public site and
# the API are not served from the same origin.
INSTITUTION_PASSWORD_RESET_URL = _env_str(
    "BACKEND_INSTITUTION_PASSWORD_RESET_URL", "/institucion/restablecer-clave"
)

# Logo shown in the HTML part of that email. Resolved the same way as the reset
# URL, with one difference that matters: this one is fetched by the recipient's
# mail client, not by a browser on the site, so it only ever renders when it
# points at a publicly reachable host. In local development it resolves to
# localhost and the client falls back to the image's alt text — set an absolute
# URL here if a local run needs the logo to load.
INSTITUTION_EMAIL_LOGO_URL = _env_str("BACKEND_EMAIL_LOGO_URL", "/favicon.png")


# Login rate limiting (django-axes)
# Locks an identity out after repeated failed logins to blunt brute-force
# attacks on the admin login page. See docs/admin-security-hardening.md.
AXES_ENABLED = _env_bool("BACKEND_AXES_ENABLED", True)
AXES_FAILURE_LIMIT = _env_int("BACKEND_AXES_FAILURE_LIMIT", 5)
AXES_COOLOFF_TIME = _env_int("BACKEND_AXES_COOLOFF_HOURS", 1)  # hours
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_LOCKOUT_TEMPLATE = None


# Security hardening (environment-aware)
# Clickjacking protection: deny framing of admin pages entirely.
X_FRAME_OPTIONS = _env_str("BACKEND_X_FRAME_OPTIONS", "DENY")
SECURE_CONTENT_TYPE_NOSNIFF = True

# The following HTTPS protections are enabled by default in production
# (DEBUG off) and can be tuned per environment. They are off in local HTTP dev.
_prod = not DEBUG
SECURE_SSL_REDIRECT = _env_bool("BACKEND_SECURE_SSL_REDIRECT", _prod)
SECURE_HSTS_SECONDS = _env_int("BACKEND_SECURE_HSTS_SECONDS", 31536000 if _prod else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "BACKEND_SECURE_HSTS_INCLUDE_SUBDOMAINS", _prod
)
SECURE_HSTS_PRELOAD = _env_bool("BACKEND_SECURE_HSTS_PRELOAD", _prod)

# Trust the X-Forwarded-Proto header set by the reverse proxy that terminates
# TLS, so Django knows the original request was HTTPS.
if _env_bool("BACKEND_SECURE_PROXY_SSL_HEADER", _prod):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS configuration
# See https://github.com/adamchainz/django-cors-headers for details

cors_allowed_origins = os.getenv("BACKEND_CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in cors_allowed_origins.split(",") if origin.strip()
]
